---
title: "Biden Transition Analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: cerulean
    
---

```{r setup, include=FALSE}
library(flexdashboard)

```



Agency Review Teams
=========================================
To filter, click on the boxes at the top of the columns. To sort, use the use/down arrows by the column name. 

Row {data-width=650}
-----------------------------------------------------------------------

### Agency Review Teams  

```{r}

newnames %>%
  gt() %>%
  tab_header(
    title = "New Names from the Agency Review Team"
  ) %>%
  cols_label(
    name = "Name",
    agency = "Agency",
    on_multiple_teams = "On Multiple Teams", 
    source_of_funding = "Source Of Funding",
    most_recent_employment = "Most Recent Employment"
  )%>%
  cols_hide(
    columns = vars(
      team_lead, idstring, namestring)
  )

```



Agency Review Teams Changes 
========================================
To filter, click on the boxes at the top of the columns. To sort, use the use/down arrows by the column name. 

Row {data-width=350}
-----------------------------------------------------------------------

### Agency Review Teams Changes

```{r}
agencycount_compare %>%
  filter(change > 0)%>%
  gt() %>%
  tab_header(
    title = "Total People Appointed to Each Agency Team & Change from Previous"
  ) %>%
    cols_label(
      agency = "Agency",
      current_count = "Current Count",
      previous_count = "Previous Count",
      change = "Change"
    )

```

White House Senior Staff 
========================================
To filter, click on the boxes at the top of the columns. To sort, use the use/down arrows by the column name. 

### White House Senior Staff

```{r}
stafftotal_current <- staff_data_current %>%
  tally(n= "Total People Currently Named to WH Senior Staff")


stafftotal_previous <- staff_data_previous %>%
  tally(n = "Total People Previously Named to WH Senior Staff")

staffcountcompare <- merge(stafftotal_current, stafftotal_previous, all=TRUE)
staffcountcompare

staffcountcompare %>%
  gt() %>%
  tab_header(
    title = "Total People Currently Named to Senior Staff vs. Previous Count"
  )
```

